using Npgsql;
using PostgresOutbox.Database;

namespace PostgresOutbox.Events;

public class EventsTable
{
    public static async Task Create(string connectionString, string tableName, CancellationToken ct)
    {
        var sql = @$"
            CREATE TABLE {tableName} (
               id         INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
               event_type VARCHAR(250) NOT NULL,
               data       JSONB        NOT NULL
            );
        ";

        await using var dataSource = NpgsqlDataSource.Create(connectionString);
        await dataSource.Execute(sql, ct);
    }
}
