using Npgsql;
using PostgresOutbox.Database;

namespace PostgresOutbox.Table;

public static class EventTable
{
    public static async Task Ensure(NpgsqlDataSource dataSource, string tableName, CancellationToken ct)
    {
        var sql = @$"
            CREATE TABLE IF NOT EXISTS {tableName} (
               id         BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
               event_type VARCHAR(250) NOT NULL,
               data       JSONB        NOT NULL
            );
        ";
        await dataSource.Execute(sql, ct);
    }
}
